version: '3.8'
services:
    database:
      image: mongo
      restart: always
    api:
      build:
        context: .
        dockerfile: dockerfile
      depends_on:
        - database
      ports:
        - "4000:4000"

      


